/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;

import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.HashMap;
import java.util.Locale;
import javax.swing.JOptionPane;
import koneksi.Koneksi;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author IT
 */
public final class menu extends javax.swing.JFrame {
    Connection conn = Koneksi.getConnection();
    
    /**
     * Creates new form utama
     */
    public menu() {
        initComponents();
        Locale locale = new Locale ("id","ID");
        Locale.setDefault(locale);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DESKTOP = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        MENUBAR = new javax.swing.JMenuBar();
        LOG = new javax.swing.JMenu();
        keluar = new javax.swing.JMenuItem();
        home = new javax.swing.JMenuItem();
        MASTER = new javax.swing.JMenu();
        user = new javax.swing.JMenuItem();
        Isupplier = new javax.swing.JMenuItem();
        Barang = new javax.swing.JMenuItem();
        TRANSAKSI = new javax.swing.JMenu();
        itempenjualan = new javax.swing.JMenuItem();
        itempembelian = new javax.swing.JMenuItem();
        LAPORAN = new javax.swing.JMenu();
        Suplier = new javax.swing.JMenuItem();
        lapbarang = new javax.swing.JMenuItem();
        penjualan = new javax.swing.JMenuItem();
        pembelian = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        notajual = new javax.swing.JMenuItem();
        Notabeli = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("| MENU UTAMA");

        DESKTOP.setBackground(new java.awt.Color(204, 204, 204));
        DESKTOP.setPreferredSize(new java.awt.Dimension(1260, 605));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Warung Sembako Cemara");

        jLabel4.setFont(new java.awt.Font("Maiandra GD", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Kepuasan Pelanggan Prioritas Kami");

        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1250, Short.MAX_VALUE))
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(272, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        DESKTOP.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout DESKTOPLayout = new javax.swing.GroupLayout(DESKTOP);
        DESKTOP.setLayout(DESKTOPLayout);
        DESKTOPLayout.setHorizontalGroup(
            DESKTOPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DESKTOPLayout.setVerticalGroup(
            DESKTOPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        LOG.setText("File");
        LOG.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        keluar.setText("Logout");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        LOG.add(keluar);

        home.setText("Home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        LOG.add(home);

        MENUBAR.add(LOG);

        MASTER.setText("Master");
        MASTER.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        user.setText("Data User");
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        MASTER.add(user);

        Isupplier.setText("Data Supplier");
        Isupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IsupplierActionPerformed(evt);
            }
        });
        MASTER.add(Isupplier);

        Barang.setText("Data Barang");
        Barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarangActionPerformed(evt);
            }
        });
        MASTER.add(Barang);

        MENUBAR.add(MASTER);

        TRANSAKSI.setText("Transaksi");
        TRANSAKSI.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TRANSAKSI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TRANSAKSIActionPerformed(evt);
            }
        });

        itempenjualan.setText("Penjualan");
        itempenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itempenjualanActionPerformed(evt);
            }
        });
        TRANSAKSI.add(itempenjualan);

        itempembelian.setText("Pembelian");
        itempembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itempembelianActionPerformed(evt);
            }
        });
        TRANSAKSI.add(itempembelian);

        MENUBAR.add(TRANSAKSI);

        LAPORAN.setText("Laporan");
        LAPORAN.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LAPORAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LAPORANActionPerformed(evt);
            }
        });

        Suplier.setText("Laporan Data Suplier");
        Suplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuplierActionPerformed(evt);
            }
        });
        LAPORAN.add(Suplier);

        lapbarang.setText("Laporan Data Barang");
        lapbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lapbarangActionPerformed(evt);
            }
        });
        LAPORAN.add(lapbarang);

        penjualan.setText("Laporan Penjualan");
        penjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penjualanActionPerformed(evt);
            }
        });
        LAPORAN.add(penjualan);

        pembelian.setText("Laporan Pembelian");
        pembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pembelianActionPerformed(evt);
            }
        });
        LAPORAN.add(pembelian);

        MENUBAR.add(LAPORAN);

        jMenu1.setText("Cetak Nota");
        jMenu1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        notajual.setText("Penjualan");
        notajual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notajualActionPerformed(evt);
            }
        });
        jMenu1.add(notajual);

        Notabeli.setText("Pembelian");
        Notabeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NotabeliActionPerformed(evt);
            }
        });
        jMenu1.add(Notabeli);

        MENUBAR.add(jMenu1);

        setJMenuBar(MENUBAR);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DESKTOP, javax.swing.GroupLayout.DEFAULT_SIZE, 1270, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DESKTOP, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        //TODO add your handling code here:
        user u = new user();
        DESKTOP.add(u);
        u.setVisible(true);
    }//GEN-LAST:event_userActionPerformed

    private void IsupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IsupplierActionPerformed
        // TODO add your handling code here:
        supplier s = new supplier();
        DESKTOP.add(s);
        s.setVisible(true);
    }//GEN-LAST:event_IsupplierActionPerformed

    private void BarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarangActionPerformed
        // TODO add your handling code here:
        barang b = new barang();
        DESKTOP.add(b);
        b.setVisible(true);
    }//GEN-LAST:event_BarangActionPerformed

    private void itempenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itempenjualanActionPerformed
        // TODO add your handling code here:
        penjualan t = new penjualan();
        DESKTOP.add(t);
        t.setVisible(true); 
    }//GEN-LAST:event_itempenjualanActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
      int selectedOption = JOptionPane.showConfirmDialog(null,
 "Apakah anda ingin Logout", "Tutup Aplikasi", JOptionPane.YES_NO_OPTION);
 if (selectedOption == JOptionPane.YES_OPTION) {
 System.exit(0);
 }
        
    }//GEN-LAST:event_keluarActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        menu a = new menu();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_homeActionPerformed

    private void lapbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lapbarangActionPerformed
        // TODO add your handling code here:
         try {
            String NamaFile = "src/laporan/barang.jasper";
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost/db_sembako","root","");
            HashMap param = new HashMap();
            JasperPrint JPrint = JasperFillManager.fillReport(NamaFile, param, koneksi);
            JasperViewer.viewReport(JPrint, false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data tidak dapat dicetak!","Cetak Data",JOptionPane.ERROR_MESSAGE);
        
    }
        
    }//GEN-LAST:event_lapbarangActionPerformed

    private void LAPORANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LAPORANActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LAPORANActionPerformed

    private void TRANSAKSIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TRANSAKSIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TRANSAKSIActionPerformed

    private void itempembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itempembelianActionPerformed
        // TODO add your handling code here:
        pembelian t = new pembelian();
        DESKTOP.add(t);
        t.setVisible(true);
    }//GEN-LAST:event_itempembelianActionPerformed

    private void notajualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notajualActionPerformed
        // TODO add your handling code here:
        lpnota_jual n = new lpnota_jual();
        n.setVisible(true);
        
    }//GEN-LAST:event_notajualActionPerformed

    private void NotabeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NotabeliActionPerformed
        // TODO add your handling code here:
        lpnota_beli b = new lpnota_beli();
        b.setVisible(true);
    }//GEN-LAST:event_NotabeliActionPerformed

    private void penjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penjualanActionPerformed
        // TODO add your handling code here:
        lppenjualan p = new lppenjualan();
        p.setVisible(true);
    }//GEN-LAST:event_penjualanActionPerformed

    private void pembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pembelianActionPerformed
        // TODO add your handling code here:
        lppembelian p = new lppembelian();
        p.setVisible(true);
    }//GEN-LAST:event_pembelianActionPerformed

    private void SuplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuplierActionPerformed
        // TODO add your handling code here:
        try {
            String NamaFile = "src/laporan/supplier.jasper";
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost/db_sembako","root","");
            HashMap param = new HashMap();
            JasperPrint JPrint = JasperFillManager.fillReport(NamaFile, param, koneksi);
            JasperViewer.viewReport(JPrint, false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data tidak dapat dicetak!","Cetak Data",JOptionPane.ERROR_MESSAGE);
        
    }
        
    }//GEN-LAST:event_SuplierActionPerformed
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new menu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Barang;
    private javax.swing.JDesktopPane DESKTOP;
    private javax.swing.JMenuItem Isupplier;
    private javax.swing.JMenu LAPORAN;
    private javax.swing.JMenu LOG;
    private javax.swing.JMenu MASTER;
    private javax.swing.JMenuBar MENUBAR;
    private javax.swing.JMenuItem Notabeli;
    private javax.swing.JMenuItem Suplier;
    private javax.swing.JMenu TRANSAKSI;
    private javax.swing.JMenuItem home;
    private javax.swing.JMenuItem itempembelian;
    private javax.swing.JMenuItem itempenjualan;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem keluar;
    private javax.swing.JMenuItem lapbarang;
    private javax.swing.JMenuItem notajual;
    private javax.swing.JMenuItem pembelian;
    private javax.swing.JMenuItem penjualan;
    private javax.swing.JMenuItem user;
    // End of variables declaration//GEN-END:variables
}
